SOURCE_DETECTION_RULES = {
    "python": [
        {"pattern": r"Crypto\.Cipher\.DES", "algorithm": "DES", "risk": "critical"},
        {"pattern": r"Crypto\.Cipher\.ARC4", "algorithm": "RC4", "risk": "critical"},
        {"pattern": r"Crypto\.Cipher\.AES", "algorithm": "AES", "risk": "medium"},
        {"pattern": r"cryptography.*AES", "algorithm": "AES", "risk": "medium"},
        {"pattern": r"Crypto\.PublicKey\.RSA", "algorithm": "RSA", "risk": "critical"},
        {"pattern": r"cryptography.*rsa", "algorithm": "RSA", "risk": "critical"},
        {"pattern": r"Crypto\.PublicKey\.ECC", "algorithm": "ECC", "risk": "critical"},
        {"pattern": r"cryptography.*ec\.", "algorithm": "ECDSA", "risk": "critical"},
        {"pattern": r"hashlib\.md5\(", "algorithm": "MD5", "risk": "critical"},
        {"pattern": r"hashlib\.sha1\(", "algorithm": "SHA-1", "risk": "critical"},
        {"pattern": r"ssl\.PROTOCOL_TLSv1", "algorithm": "TLSv1", "risk": "critical"},
        {"pattern": r"ssl\.PROTOCOL_SSLv3", "algorithm": "SSLv3", "risk": "critical"},
    ],
    "java": [
        {"pattern": r'Cipher\.getInstance\("RSA', "algorithm": "RSA", "risk": "critical"},
        {"pattern": r'Cipher\.getInstance\("DES', "algorithm": "DES", "risk": "critical"},
        {"pattern": r'KeyPairGenerator\.getInstance\("RSA"\)', "algorithm": "RSA", "risk": "critical"},
        {"pattern": r'KeyPairGenerator\.getInstance\("EC"\)', "algorithm": "ECC", "risk": "critical"},
        {"pattern": r'KeyPairGenerator\.getInstance\("DSA"\)', "algorithm": "DSA", "risk": "critical"},
        {"pattern": r'MessageDigest\.getInstance\("MD5"\)', "algorithm": "MD5", "risk": "critical"},
        {"pattern": r'MessageDigest\.getInstance\("SHA-1"\)', "algorithm": "SHA-1", "risk": "critical"},
        {"pattern": r'Signature\.getInstance\("SHA1withRSA"\)', "algorithm": "SHA-1+RSA", "risk": "critical"},
    ],
    "c": [
        {"pattern": r"RSA_generate_key", "algorithm": "RSA", "risk": "critical"},
        {"pattern": r"RSA_new", "algorithm": "RSA", "risk": "critical"},
        {"pattern": r"EVP_PKEY_RSA", "algorithm": "RSA", "risk": "critical"},
        {"pattern": r"DSA_generate_parameters", "algorithm": "DSA", "risk": "critical"},
        {"pattern": r"DH_new", "algorithm": "DH", "risk": "critical"},
        {"pattern": r"EC_KEY_new", "algorithm": "ECC", "risk": "critical"},
        {"pattern": r"DES_set_key", "algorithm": "DES", "risk": "critical"},
        {"pattern": r"DES_ecb_encrypt", "algorithm": "DES", "risk": "critical"},
        {"pattern": r"RC4_set_key", "algorithm": "RC4", "risk": "critical"},
        {"pattern": r"MD5_Init", "algorithm": "MD5", "risk": "critical"},
        {"pattern": r"SHA1_Init", "algorithm": "SHA-1", "risk": "critical"},
        {"pattern": r"TLSv1_method\(", "algorithm": "TLSv1", "risk": "critical"},
        {"pattern": r"SSLv3_method\(", "algorithm": "SSLv3", "risk": "critical"},
    ],
    "cpp": [
        {"pattern": r"RSA_generate_key", "algorithm": "RSA", "risk": "critical"},
        {"pattern": r"RSA_new", "algorithm": "RSA", "risk": "critical"},
        {"pattern": r"EVP_PKEY_RSA", "algorithm": "RSA", "risk": "critical"},
        {"pattern": r"DSA_generate_parameters", "algorithm": "DSA", "risk": "critical"},
        {"pattern": r"DH_new", "algorithm": "DH", "risk": "critical"},
        {"pattern": r"EC_KEY_new", "algorithm": "ECC", "risk": "critical"},
        {"pattern": r"DES_set_key", "algorithm": "DES", "risk": "critical"},
        {"pattern": r"DES_ecb_encrypt", "algorithm": "DES", "risk": "critical"},
        {"pattern": r"RC4_set_key", "algorithm": "RC4", "risk": "critical"},
        {"pattern": r"MD5_Init", "algorithm": "MD5", "risk": "critical"},
        {"pattern": r"SHA1_Init", "algorithm": "SHA-1", "risk": "critical"},
        {"pattern": r"TLSv1_method\(", "algorithm": "TLSv1", "risk": "critical"},
        {"pattern": r"SSLv3_method\(", "algorithm": "SSLv3", "risk": "critical"},
    ],
    "javascript": [
        {"pattern": r"crypto\.createCipheriv\('des", "algorithm": "DES", "risk": "critical"},
        {"pattern": r"crypto\.createCipheriv\('rc4", "algorithm": "RC4", "risk": "critical"},
        {"pattern": r"crypto\.generateKeyPair\('rsa", "algorithm": "RSA", "risk": "critical"},
        {"pattern": r"crypto\.generateKeyPair\('ec", "algorithm": "ECC", "risk": "critical"},
        {"pattern": r"crypto\.createHash\('md5'\)", "algorithm": "MD5", "risk": "critical"},
        {"pattern": r"crypto\.createHash\('sha1'\)", "algorithm": "SHA-1", "risk": "critical"},
        {"pattern": r"require\(['\"]node-rsa['\"]\)", "algorithm": "RSA", "risk": "critical"},
        {"pattern": r"require\(['\"]jsrsasign['\"]\)", "algorithm": "RSA", "risk": "critical"},
    ],
    "typescript": [
        {"pattern": r"crypto\.createCipheriv\('des", "algorithm": "DES", "risk": "critical"},
        {"pattern": r"crypto\.createCipheriv\('rc4", "algorithm": "RC4", "risk": "critical"},
        {"pattern": r"crypto\.generateKeyPair\('rsa", "algorithm": "RSA", "risk": "critical"},
        {"pattern": r"crypto\.generateKeyPair\('ec", "algorithm": "ECC", "risk": "critical"},
        {"pattern": r"crypto\.createHash\('md5'\)", "algorithm": "MD5", "risk": "critical"},
        {"pattern": r"crypto\.createHash\('sha1'\)", "algorithm": "SHA-1", "risk": "critical"},
    ],
}

CERT_EXTENSIONS = {".pem", ".crt", ".cer", ".der", ".p12", ".pfx", ".jks"}

EXCLUDE_DIRS = {"node_modules", ".git", "venv", "__pycache__", "dist", "build", "target"}

LANGUAGE_EXTENSIONS = {
    ".py": "python",
    ".java": "java",
    ".c": "c",
    ".cpp": "cpp",
    ".h": "c",
    ".hpp": "cpp",
    ".js": "javascript",
    ".ts": "typescript",
}